model:
  vae:
    name: vae
    coord_dim: 3
    hidden_dim: 64
    latent_dim: 32
    norm_type: layer
    ckpt_path: ckpts/vae.ckpt

val:
  data_mode: val
  use_random: true 
  seed: 2026
  batch_size: 1

dataset:
  use_rotate: false
  use_tag: false
  train_file: /root/autodl-fs-data3/Articulation-XL2.0/train_meta.json
  val_file: /root/autodl-fs-data3/Articulation-XL2.0/val_meta.json
