model:
  diffusion:
    latent_dim: 32
    hidden_dim: 768
    depth: 8
    heads: 12
    num_steps: 1000
    objective: "pred_noise"
    norm_type: layer
    dropout: 0
    cfg_scale: 7.0
    min_snr_loss_weight: False
    min_snr_gamma: 1
    ckpt_path: ckpts/skdiff.pt

  vae:
    coord_dim: 3
    hidden_dim: 64
    latent_dim: 32
    norm_type: layer
    ckpt_path: ckpts/vae.pt

  clip:
    clip_embed_dim: 768
    ckpt_path: openai/clip-vit-large-patch14

val:
  data_mode: val
  use_random: true
  use_text: true
  seed: 2026
  batch_size: 5000
  num_workers: 32
  default_view: xz

dataset:
  name: node
  use_rotate: false
  val_file: datasets/test_common_meta.json

output_dir: outputs/vis_xz
skeleton_output_base_dir: outputs/skeleton_xz