model:
  vae:
    name: vae
    coord_dim: 3
    hidden_dim: 64
    latent_dim: 32
    norm_type: layer
    ckpt_path: ckpts/Sk-VAE.pt

val:
  data_mode: val
  use_random: true 
  seed: 2026
  batch_size: 1

dataset:
  use_rotate: false
  use_tag: false
  train_file: datasets/train_meta.json
  val_file: datasets/val_meta.json
