model:
  diffusion:
    latent_dim: 32
    hidden_dim: 768
    depth: 8
    heads: 12
    num_steps: 1000
    objective: "pred_noise"
    norm_type: layer
    dropout: 0.1
    uncond_prob: 0.1
    cfg_scale: 7.0
    min_snr_loss_weight: False
    min_snr_gamma: 1

  vae:
    coord_dim: 3
    hidden_dim: 64
    latent_dim: 32
    norm_type: layer
    ckpt_path: ckpts/vae.pt

  clip:
    clip_embed_dim: 768
    ckpt_path: openai/clip-vit-large-patch14

train:
  seed: 2026
  batch_size: 128
  num_workers: 4
  pin_memory: True
  max_iters: 400000
  val_freq: 50000
  max_grad_norm: 1.0
  use_amp: false
  use_tag: true
  optimizer:
    type: adamw
    lr: 1.e-4
    weight_decay: 1.e-4
    beta1: 0.9
    beta2: 0.999

  scheduler:
    type: warmup_cosineannealing
    warmup_iter: 2000 
    T_max: 400000
    eta_min: 0

  ema_decay: 0.9999

log_dir: logs

dataset:
  use_rotate: true
  use_tag: true
  train_file: datasets/train_meta.json
  val_file: datasets/val_meta.json
